### ISSUE TITLE
Hadoop install hooks fail behind restricted network

### ISSUE THREAD

**Issue by jogeo** [juju-solutions/layer-hadoop-base#12]
Charms in the apache-core-batch-processing bundle fail in the install hook due to the setuptools_scm dependency. juju-resource does not help because resources.yaml does not include setuptools_scm.

Affected charms in the apache-core-batch-processing bundle are:
    cs:trusty/apache-hadoop-namenode
    cs:trusty/apache-hadoop-resourcemanager
    cs:trusty/apache-hadoop-slave
    cs:trusty/apache-hadoop-plugin
    cs:trusty/hadoop-client

The charms continuously attempt to install, cycling through:
    maintenance --> executing --> error

$ juju status-history -n 200 slave/0
TIME                    TYPE        STATUS      MESSAGE  
31 May 2016 22:34:46Z   juju-unit   allocating  
31 May 2016 22:34:46Z   workload    unknown     Waiting for agent initialization to finish
31 May 2016 22:43:08Z   workload    maintenance installing charm software  
31 May 2016 22:43:08Z   juju-unit   executing   running install hook  
31 May 2016 22:50:57Z   juju-unit   error       hook failed: "install"  
31 May 2016 22:51:02Z   workload    maintenance installing charm software  
31 May 2016 22:51:02Z   juju-unit   executing   running install hook  
31 May 2016 22:57:25Z   juju-unit   error       hook failed: "install"

[unit-slave-0.log.txt](https://github.com/juju-solutions/layer-hadoop-base/files/292674/unit-slave-0.log.txt)

**Comment by ktsakalozos** [comment]
Thank you for reporting this.

We have seen this issue before https://github.com/juju-solutions/layer-apache-hadoop-namenode/issues/7

And we have patched it in jujubigdata library version 6.4.2 https://github.com/juju-solutions/jujubigdata/commit/eaa749dea565e21c043e554740e053246728faba

Unfortunately bundle https://jujucharms.com/apache-core-batch-processing/ points to cs:trusty/apache-hadoop-namenode-1 that comes together with jujubigdata library v6.4.1 

We created a ticket to go over our bundles and make sure they are updated and in good shape. 

Apologies for the inconvenience.

**Comment by jogeo** [comment]
Do you have an ETA on when bundles will be ready?

**Comment by ktsakalozos** [comment]
The task is already in the "doing" state on our board. It should be a matter of days.

**Comment by ktsakalozos** [comment]
The apache-core-batch-processing bunlde has been renamed to apache-processing-mapreduce
We just promulgated the new mapreduce processing bundle here https://jujucharms.com/apache-processing-mapreduce/bundle/1 

Alternatively you could use the spark bundle found: https://jujucharms.com/apache-processing-spark/bundle/1

Both bundles target production grade deployment therefore they come packed with monitoring options and HA

Thanks
