### ISSUE TITLE
some hdfs-site.xml config bits belong here

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/layer-hadoop-base#8]
Settings like replication and blocksize affect clients at runtime (like `dfs -copyFromLocal`), and should be on the the plugin since that is the endpoint where we expect users to interact with hdfs (either via the client or client charms like spark):

https://github.com/juju-solutions/layer-apache-hadoop-plugin/pull/5 **(need review)**

These settings had no effect on clients when set on the namenode, nor do they become defaults for the cluster even after NN is restarted with these settings.  So I removed these from jbd's configure_namenode and from the namenode charm:

https://github.com/juju-solutions/jujubigdata/commit/016ad56d7d0087657041ea1588935648e110e1d9
https://github.com/juju-solutions/layer-apache-hadoop-namenode/pull/14 **(need review)**

These definitely belong on the plugin, but could potentially belong on any charm with an /etc/hadoop/conf/hdfs-site.xml.  In support of this, I added functionality to reconfigure hdfs-site.xml to hadoop-base. Atm, only plugin calls this:

https://github.com/juju-solutions/layer-hadoop-base/commit/ebbc63e4eeccfc8b17440676b15a8e0a89e5514a

**Comment by kwmonroe** [comment]
Tested successfully:

**change to 64MB block size, default replication**

```
$ juju set-config pl dfs_blocksize=67108864
ubuntu@pl-0:~$ hdfs dfs -copyFromLocal /etc/passwd /user/ubuntu/passwd
ubuntu@pl-0:~$ hdfs dfs -stat "%n %o %r" /user/ubuntu/passwd*
passwd 67108864 3
```

**change to repl=2, keep block size**

```
$ juju set-config pl dfs_replication=2
ubuntu@pl-0:~$ hdfs dfs -copyFromLocal /etc/passwd /user/ubuntu/passwd2
ubuntu@pl-0:~$ hdfs dfs -stat "%n %o %r" /user/ubuntu/passwd*
passwd 67108864 3
passwd2 67108864 2
```

**change to block size 128MB, keep repl**

```
$ juju set-config pl dfs_blocksize=134217728
ubuntu@pl-0:~$ hdfs dfs -copyFromLocal /etc/passwd /user/ubuntu/passwd3
ubuntu@pl-0:~$ hdfs dfs -stat "%n %o %r" /user/ubuntu/passwd*                                                                
passwd 67108864 3
passwd2 67108864 2
passwd3 134217728 2
```

**Comment by johnsca** [comment]
+1 all merged.
